### ISSUE TITLE
[Swift/Cocoapods] use_frameworks!使用時のimport

### ISSUE THREAD

**Issue by masuhara** [KiiCorp/KiiCloudSDK-iOS#27]
SwiftのプロジェクトでCocoapodsを使ったときに、frameworkをBridging-headerを使わずにPodfileで# use_frameworks!を外してから使用する場合、import Kii(import KiiSDK)と書いても「No such module 'Kii')と出てimportできません。

KiiCloudSDK-iOSはCocoaPods経由で入れるとBridging-Headerを内包しているような気がしますが、こういった状況でうまくimportする方法がありますでしょうか？

**Comment by yongpingchen** [comment]
@masuhara 
`KiiCloud` framework はdynamic framework ではないので、`use_frameworks!` をcommentをしてください。

`pod install` をしてから、ブリッジヘッダーファイルも追加してください。手順はこの[プログラムの記述](http://docs.kii.com/ja/guides/ios/quickstart/install-sdk/#プログラムの記述)を参考してください。

ブリッジヘッダーファイルに`#import <KiiSDK/KiiSDK-Bridging-Header.h>`を追加してから、`import Kii(import KiiSDK)`をしず、KiiCloud のクラスを使えます

**Comment by masuhara** [comment]
@yongpingchen 
お返事ありがとうございます。理解しました。
別ライブラリとの組み合わせ上、Bridging-Headerを使いたくないので、use_frameworks!で使えるようになることを期待しています。よろしくお願いいたします。

**Comment by yongpingchen** [comment]
@masuhara 2.6.0からdynamic frameworkになります。ご確認ください
